import dotenv from "dotenv";
dotenv.config();
const SECRET_KEY = process.env.JWT_SECRET!;
const PORT = process.env.PORT || 3000;
const DB_HOST = process.env.DB_HOST;
const DB_USER = process.env.DB_USER;
const DB_PASSWORD = process.env.DB_PASSWORD;
const DB_PORT = process.env.DB_PORT;
const DB_NAME = process.env.DB_NAME;
export { SECRET_KEY, PORT, DB_HOST, DB_PASSWORD, DB_PORT, DB_USER, DB_NAME };
